apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api.yaml
  - worker.yaml
commonLabels:
  app.kubernetes.io/name: earth-intelligence-os
  app.kubernetes.io/part-of: earth-intelligence
